repos:
  - repo: local
    hooks:
      - id: ruff-format
        name: ruff format
        entry: uv run --no-sync --group dev ruff format --force-exclude
        language: system
        types_or:
          - python
          - pyi

      - id: ruff-check
        name: ruff check
        entry: uv run --no-sync --group dev ruff check --fix --force-exclude
        language: system
        types_or:
          - python
          - pyi

      - id: mypy
        name: mypy
        entry: uv run --no-sync --group dev mypy
        language: system
        always_run: true
        pass_filenames: false
